export const CONSTANT_THAT_SAYS_REQUEST = 'CONSTANT_THAT_SAYS_REQUEST'
export const CONSTANT_THAT_SAYS_SUCCESS = 'CONSTANT_THAT_SAYS_SUCCESS'
export const CONSTANT_THAT_SAYS_FAIL = 'CONSTANT_THAT_SAYS_FAIL'
export const CONSTANT_THAT_SAYS_RESET = 'RETRIEVE_CATEGORIES_RESET'